---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/output_vars
    - name: Import vprofile setup variables
      include_vars: vars/vprostacksetup
    - name: Create vprofile key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out
    - name: Save private key into file vprokey.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./vprokey.pem"
        mode: 0600
      when: vprokey_out.changed    
