---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/output_vars
    - name: Import vprofile setup variables
      include_vars: vars/vprostacksetup
    - name: Create vprofile key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out
    - name: Save private key into file vprokey.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./vprokey.pem"
        mode: 0600
      when: vprokey_out.changed
    - name: Create securiy groups for ELB
      ec2_group:
        name: vpro_ELB
        description: Allow port 80 from all port 
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rule:
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
      register: vproELB-SG
    - name: Create securiy groups for Vprofile Stack
      ec2_group:
        name: vpro_SG
        description: Allow port 22 from all port 
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rule:
         - proto: tcp
           from_port: 80
           to_port: 80
           group_id: "{{vproELB-SG.group_id}}"
         - proto: tcp
           from_port: 22
           to_port: 22
           group_id: "{{bastionSG}}" 
      register: vprostackSG_out      


